const express = require("express");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const cors = require("cors");
const axios = require("axios");
const FormData = require("form-data");
const mongoose = require("mongoose");
const authRoutes = require("./routes/auth");
const authMiddleware = require("./middleware/auth");

const app = express();
const PORT = process.env.PORT || 3000;
const MONGODB_URI = "mongodb://127.0.0.1:27017/brain_tumor_db";

const sanitizeFilename = (name) =>
  String(name)
    .replace(/[^a-zA-Z0-9._-]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");

// MongoDB connection
mongoose
  .connect(MONGODB_URI)
  .then(() => {
    console.log("✅ MongoDB connected successfully to", MONGODB_URI);
  })
  .catch((error) => {
    console.error("❌ MongoDB connection error:", error.message);
    process.exit(1);
  });

// Mongoose schema for Prediction
const predictionSchema = new mongoose.Schema({
  patientName: {
    type: String,
    required: true,
  },
  tumorType: {
    type: String,
    required: true,
  },
  confidence: {
    type: Number,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  imagePath: {
    type: String,
    required: false,
  },
  imageUrl: {
    type: String,
    required: false,
  },
});

const Prediction = mongoose.model("Prediction", predictionSchema);

// Configure CORS
app.use(
  cors({
    origin: "*",
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"],
  }),
);

// Parse JSON bodies
app.use(express.json());
app.use("/api/auth", authRoutes);

// Serve static heatmap files generated by FastAPI
app.use('/heatmaps', express.static(path.join(__dirname, '../heatmaps')));

// Serve uploaded MRI images
app.use("/uploads", express.static(path.join(__dirname, "uploads")));

// Make sure uploads directory exists
const uploadsDir = path.join(__dirname, "uploads");
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir);
}

// Configure multer for disk storage
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, uploadsDir);
  },
  filename: function (req, file, cb) {
    const safeOriginal = sanitizeFilename(file.originalname);
    cb(null, `${Date.now()}-${safeOriginal}`);
  },
});
const upload = multer({
  storage: storage,
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB limit
  },
  fileFilter: (req, file, cb) => {
    // Accept only image files
    const allowedMimes = ["image/jpeg", "image/jpg", "image/png"];
    if (allowedMimes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(
        new Error(
          "Invalid file type. Only JPEG and PNG images are allowed.",
        ),
      );
    }
  },
});

// Health check endpoint
app.get("/health", (req, res) => {
  res.json({ status: "ok", message: "Express server is running" });
});

// Predict endpoint
app.post("/api/predict", authMiddleware, upload.single("file"), async (req, res) => {
  try {
    // Check if file was uploaded
    if (!req.file) {
      return res.status(400).json({
        error: "No file uploaded. Please provide an image file.",
      });
    }

    // Get patientName from request body
    const { patientName } = req.body;
    if (!patientName || patientName.trim() === "") {
      return res.status(400).json({
        error: "Patient name is required. Please provide a patient name.",
      });
    }

    // Create FormData to forward to FastAPI server
    const formData = new FormData();
    // Read the file from disk to send to FastAPI
    formData.append("file", fs.createReadStream(req.file.path), {
      filename: req.file.originalname,
      contentType: req.file.mimetype,
    });

    // Forward request to FastAPI server
    const fastApiUrl = "http://localhost:8000/predict/";

    const response = await axios.post(fastApiUrl, formData, {
      headers: {
        ...formData.getHeaders(),
      },
      timeout: 30000, // 30 second timeout
    });

    console.log("FastAPI response:", response.data);

    // Extract prediction data from FastAPI response
    const tumorType = response.data.prediction;
    const confidence = response.data.confidence;
    const heatmap = response.data.heatmap;

    const imageUrl = `/uploads/${req.file.filename}`;

    // Save prediction to MongoDB
    const prediction = new Prediction({
      patientName: patientName.trim(),
      tumorType: tumorType,
      confidence: confidence,
      imagePath: req.file.path.replace(/\\/g, '/'), // normalize path for consistent DB storage
      imageUrl,
    });

    const savedPrediction = await prediction.save();
    console.log(
      `✅ Prediction saved to MongoDB: Patient: ${patientName}, Tumor Type: ${tumorType}, Confidence: ${confidence}, ID: ${savedPrediction._id}`,
    );

    // Return the prediction result from FastAPI (plus image URL)
    res.json({
      ...response.data,
      imageUrl,
    });
  } catch (error) {
    console.error("Error processing prediction:", error.message);

    // Handle different error types
    if (error.code === "ECONNREFUSED") {
      return res.status(503).json({
        error:
          "FastAPI server is not available. Please ensure it is running on http://localhost:8000",
      });
    }

    if (error.response) {
      // FastAPI server returned an error
      return res.status(error.response.status).json({
        error: error.response.data.error || "Error from FastAPI server",
      });
    }

    if (error.code === "ETIMEDOUT" || error.code === "ECONNABORTED") {
      return res.status(504).json({
        error: "Request timeout. The FastAPI server took too long to respond.",
      });
    }

    // Handle MongoDB errors
    if (error instanceof mongoose.Error) {
      return res.status(500).json({
        error: "Database error occurred while saving prediction.",
      });
    }

    // Generic error
    res.status(500).json({
      error:
        error.message ||
        "Internal server error occurred while processing the prediction",
    });
  }
});

// History endpoint - Get all predictions sorted by newest first
app.get("/api/history", authMiddleware, async (req, res) => {
  try {
    const predictions = await Prediction.find()
      .sort({ createdAt: -1 }) // Sort by newest first
      .exec();

    console.log(
      `✅ Retrieved ${predictions.length} prediction(s) from MongoDB`,
    );

    res.json({
      count: predictions.length,
      predictions: predictions,
    });
  } catch (error) {
    console.error("Error retrieving prediction history:", error.message);
    res.status(500).json({
      error:
        "Internal server error occurred while retrieving prediction history",
    });
  }
});

// History endpoint - Delete a prediction
app.delete("/api/history/:id", authMiddleware, async (req, res) => {
  try {
    const { id } = req.params;
    const deletedPrediction = await Prediction.findByIdAndDelete(id);

    if (!deletedPrediction) {
      return res.status(404).json({ error: "Prediction not found" });
    }

    if (deletedPrediction.imagePath && fs.existsSync(deletedPrediction.imagePath)) {
      try {
        fs.unlinkSync(deletedPrediction.imagePath);
      } catch (err) {
        console.error("Error deleting image file:", err);
      }
    }

    console.log(`✅ Deleted prediction from MongoDB: ID ${id}`);
    res.json({ message: "Prediction deleted successfully", id });
  } catch (error) {
    console.error("Error deleting prediction:", error.message);
    res.status(500).json({
      error: "Internal server error occurred while deleting prediction",
    });
  }
});

// Dashboard stats endpoint
app.get("/api/dashboard/stats", authMiddleware, async (req, res) => {
  try {
    const [total, glioma, pituitary, notumor] = await Promise.all([
      Prediction.countDocuments(),
      Prediction.countDocuments({ tumorType: { $regex: /glioma/i } }),
      Prediction.countDocuments({ tumorType: { $regex: /pituitary/i } }),
      Prediction.countDocuments({
        $or: [
          { tumorType: { $regex: /notumor/i } },
          { tumorType: { $regex: /no tumor/i } },
          { tumorType: { $regex: /normal/i } },
        ],
      }),
    ]);

    res.json({
      total,
      glioma,
      pituitary,
      notumor,
    });
  } catch (error) {
    console.error("Error retrieving dashboard stats:", error.message);
    res.status(500).json({
      error: "Internal server error occurred while retrieving dashboard stats",
    });
  }
});

// Error handling middleware for multer errors
app.use((error, req, res, next) => {
  if (error instanceof multer.MulterError) {
    if (error.code === "LIMIT_FILE_SIZE") {
      return res
        .status(400)
        .json({ error: "File too large. Maximum size is 10MB." });
    }
    return res.status(400).json({ error: error.message });
  }

  if (error) {
    return res.status(400).json({ error: error.message });
  }

  next();
});

// Start server
app.listen(PORT, () => {
  console.log(`Express server is running on http://localhost:${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
  console.log(`Predict endpoint: http://localhost:${PORT}/api/predict`);
  console.log(`History endpoint: http://localhost:${PORT}/api/history`);
});
